version: '2'
services:

  deluge:
    image: linuxserver/deluge
    restart: always
    expose:
      - "58846"
      - "8112"
      - "53160"
      - "53160/udp"
    ports:
      - "58846:58846"
      - "8112:8112"
    volumes:
      - ./downloads:/downloads
      - /etc/localtime:/etc/localtime:ro

  sonarr:
    image: linuxserver/sonarr
    restart: always
    expose:
      - "8989"
    ports:
      - "8989:8989"
    volumes:
      - ./downloads:/downloads:rw
      - ./sonarr_downloads:/tv:rw
      - ./conf/sonarrsonarr:/config:rw
      - /etc/localtime:/etc/localtime:ro

  plex:
    image: linuxserver/plex
    restart: always
    volumes:
      - ./downloads:/data
      - ./config/plex:/plex
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"